name: otter
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.11.1
  - geopandas-base=0.11.1
  - pandas=1.5.0
  - libgdal=3.4.0
  - pandas=1.5.0
  - scikit-learn=1.1.2
  - pickleshare=0.7.5
  - networkx=2.8.6
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - jupyterthemes=0.20.0
  - progressbar=2.5
